"use client";
import { FormEvent, useEffect, useState } from "react";
import { useSearchParams } from "next/navigation";
import EducationShell from "@/components/education/EducationShell";
type Challenge={id:string;competency_code:string;prompt:string;status:string};
export default function EducationTest(){
 const params=useSearchParams(); const challengeId=params.get("challengeId")??params.get("proofId")??""; const [challenge,setChallenge]=useState<Challenge|null>(null); const [answer,setAnswer]=useState(""); const [result,setResult]=useState<{independently_verified:boolean;status:string;next_best_action?:string;next_best_action_rule_id?:string;next_best_action_explanation?:string}|null>(null); const [error,setError]=useState(""); const [busy,setBusy]=useState(false);
 useEffect(()=>{if(!challengeId)return; fetch(`/api/education/proof-challenges/${encodeURIComponent(challengeId)}`,{cache:"no-store"}).then(async r=>{const p=await r.json();if(!r.ok)throw new Error(p.detail??"Proof indisponible");setChallenge(p)}).catch(e=>setError(e.message));},[challengeId]);
 async function submit(e:FormEvent){e.preventDefault();if(!challenge||!answer.trim())return;setBusy(true);setError("");try{const r=await fetch(`/api/education/proof-challenges/${encodeURIComponent(challenge.id)}/submit`,{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({answer})});const p=await r.json();if(!r.ok)throw new Error(p.detail??"Validation impossible");setResult(p);}catch(e){setError(e instanceof Error?e.message:"Validation impossible");}finally{setBusy(false)}}
 return <EducationShell active="test"><header className="rkjo-demo-header"><div><span className="rkjo-edu-kicker">ME TESTER</span><h1>Vérifie ce que tu sais réellement faire sans aide.</h1><p>Pendant une Proof, le professeur IA et les indices sont désactivés.</p></div></header><section className="rkjo-supports-workspace">{!challengeId?<div className="rkjo-activity-state"><h2>Aucune Proof à passer maintenant.</h2><p>RKJO te proposera une Proof lorsque tes réussites doivent être confirmées en autonomie.</p></div>:error?<div className="rkjo-session-error">{error}</div>:!challenge?<p>Préparation de la Proof…</p>:result?<div className={result.independently_verified?"rkjo-proof-final success":"rkjo-proof-final warning"}><strong>{result.independently_verified?"✓ Compétence démontrée en autonomie":"Compétence à renforcer"}</strong><p>{result.independently_verified?"Cette preuve peut maintenant renforcer ton niveau de maîtrise.":"RKJO doit maintenant adapter ton prochain entraînement."}</p>{result.next_best_action_explanation?<div className="rkjo-proof-intro"><strong>Prochaine action RKJO · {result.next_best_action_rule_id}</strong><p>{result.next_best_action_explanation}</p></div>:null}</div>:<form onSubmit={submit} className="rkjo-exercise-form"><span className="rkjo-competency-badge">{challenge.competency_code}</span><div className="rkjo-question-card"><strong>{challenge.prompt}</strong></div><input value={answer} onChange={e=>setAnswer(e.target.value)} placeholder="Ta réponse" autoComplete="off"/><small className="rkjo-proof-lock">🔒 Aucun indice ni professeur IA pendant cette question.</small><button className="rkjo-action-primary" disabled={busy||!answer.trim()}>{busy?"Vérification…":"Valider sans aide"}</button></form>}</section></EducationShell>;
}